Update Gsoc Guide for 2022
mattermost/mattermost-developer-documentation pull request #1017
Opened 2022-02-18 23:42 UTC by BenLloydPearson

#### Summary
Updating Google Summer of Code guide for 2022

#### Ticket Link
n/a

2022-02-19 00:16 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +This page outlines everything you need to know about contributing to Mattermost for the Google Summer of Code (GSoC).
Do we need the article? Not sure, actually, so this is more a question than a request for changes :)
```suggestion
This page outlines everything you need to know about contributing to Mattermost for Google Summer of Code (GSoC).
```

2022-02-19 00:17 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +1. Learn about our [contribution process](https://developers.mattermost.com/contribute/getting-started/). We encourage applicants to participate in one of them many contribution opportunities we have
Typo?
```suggestion
1. Learn about our [contribution process](https://developers.mattermost.com/contribute/getting-started/). We encourage applicants to participate in one of the many contribution opportunities we have prior to applying.
```

2022-02-19 00:17 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +1. Review our idea list below for any that might that interest you, all of the details are listed in GitHub Issues on our Community repository.
Typo? Also, maybe we can link at the whole list here
```suggestion
1. Review our idea list below for any that might interest you, all of the details are listed [in GitHub Issues on our Community repository](https://github.com/mattermost/community/issues?q=is%3Aissue+is%3Aopen+%22GSoC+Idea%3A%22).
```

2022-02-19 00:19 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +   * If you have general questions about participating in GSoC with Mattermost, send an email to gsoc@mattermost.com
Should we direct them to the channel first?
```suggestion
   * If you have general questions about participating in GSoC with Mattermost, ask in the [GSoC channel](https://community.mattermost.com/core/channels/google-summer-of-code) or send an email to gsoc@mattermost.com
```

2022-02-19 00:21 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +1. Sumit your application before the deadline.
These read a bit weird. What about this?
```suggestion
1. Work with the project mentors on your application: they are there to help you write a good proposal!
1. Submit your application before the deadline. Note that all applications must go through Google's official application process.
```

2022-02-19 00:21 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +    -   Elias N ([@elias.nahum](https://community.mattermost.com/core/messages/@elias.nahum))
Poor Elias does not have his last name!
```suggestion
    -   Elias Nahum ([@elias.nahum](https://community.mattermost.com/core/messages/@elias.nahum))
```

2022-02-19 00:22 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +* [Speech to Text Integration](https://github.com/mattermost/community/issues/168) - Publish a plugin to analyze the CI pipelines in Mattermost to alert the team of build and test failures
The descriptions of these are duplicated.

2022-02-19 00:22 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +* [Post Edit History](https://github.com/mattermost/community/issues/167) - Publish a plugin to view the history of edits in posts and improve message history auditing
```suggestion
* [Post Edit History](https://github.com/mattermost/community/issues/167) - Publish a plugin to view the history of edits in posts and improve message history auditing.
```

2022-02-19 00:23 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +* [Custom keyboard shortcuts](https://github.com/mattermost/community/issues/162) - Design and implement a system to let users customize their keyboard shortcuts
```suggestion
* [Custom keyboard shortcuts](https://github.com/mattermost/community/issues/162) - Design and implement a system to let users customize their keyboard shortcuts.
```

2022-02-19 00:24 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +Ideas proposed by students are more than welcome, don’t hesitate to send them our way! As with all the other projects, you need to take into account that the proposals would need to fit in the overal
This year they might not be students :)
```suggestion
Ideas proposed by contributors are more than welcome, don’t hesitate to send them our way! As with all the other projects, you need to take into account that the proposals would need to fit in the overall philosophy of the project: Our product managers will take a look before we can approve them, and we can always discuss the details with the whole team if we decide to move forward with it.
```

2022-02-19 00:24 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +).
Formatting:
```suggestion
If you want to propose your own idea, share your idea as early as possible in our [GSoC channel](https://community.mattermost.com/core/channels/google-summer-of-code).
```

2022-02-19 00:27 UTC, agarciamontoro commented
Whoops, and the title seems duplicated (the title of the page and the first heading are the same). What do you think if we have two h1 headings: the first would be "Contributor guidance" (or something similar) and the second one would be "Ideas list". Thoughts?
![image](https://user-images.githubusercontent.com/3924815/154777930-81f84f1c-15ea-4813-94ee-9336d952ba0a.png)

2022-02-21 15:33 UTC, BenLloydPearson commented
@agarciamontoro I committed all of your suggested changes and fixed the duplicated title.

2022-02-21 15:38 UTC, agarciamontoro requested changes
Looking great, thank you for addressing the changes!

2022-02-21 15:38 UTC, agarciamontoro commented on site/content/contribute/gsoc/_index.md
> +    -    Claudio Costa ([@claudio.costa](https://community.mattermost.com/core/messages/@claudio.costa))
Just one more addition and I think we can merge! :tada:
```suggestion
    -    Claudio Costa ([@claudio.costa](https://community.mattermost.com/core/messages/@claudio.costa))
    -    Ibrahim Acikgoz ([@ibrahim.acikgoz](https://community-daily.mattermost.com/core/messages/@ibrahim.acikgoz))
```

2022-02-21 16:02 UTC, agarciamontoro approved these changes
:tada:

2022-02-21 16:20 UTC, streamer45 approved these changes
Looks great :+1: 

My only suggestion would be to possibly ask for a quick pass from our writers team. Can be done post merge if this needs to go in asap.

2022-02-21 16:27 UTC, agarciamontoro commented
@streamer45, yup, I'll ask @cwarnermm or @justinegeffen for a review post-merge! We want to have it merged now, so we can review it post-merge. 

Thanks for the review! :tada:

2022-02-21 16:28 UTC, merged