updated e2e guide for writing
mattermost/mattermost-developer-documentation pull request #1048
Opened 2022-03-21 22:31 UTC by furqanmlk

#### Summary
Updated instructions for `If test case is failing due to Known Issue` in webapp and mobile e2e guides

2022-03-22 06:29 UTC, saturninoabril requested changes
Thanks @furqanmlk! Overall looks good to me. Please see suggestions.

2022-03-22 06:29 UTC, saturninoabril commented on site/content/contribute/mobile/e2e/guide-for-writing.md
> +   1. append the Jira issue key in the test description, following the format of ` -- KNOWN ISSUE: [Jira_key]`. For example,
```suggestion
   1. Append the Jira issue key in the test title, following the format of ` -- KNOWN ISSUE: [Jira_key]`. For example,
```

2022-03-22 06:29 UTC, saturninoabril commented on site/content/contribute/mobile/e2e/guide-for-writing.md
> +   1. move the test case into a sperate `spec` file, following the format of `<existting spec file name_[1-9].js>`. For example,
```suggestion
   2. Move the test case into a separate `spec` file following the format of `<existing_spec_file_name_[1-9].js>`. For example,
```

2022-03-22 06:29 UTC, saturninoabril commented on site/content/contribute/mobile/e2e/guide-for-writing.md
> +   1. if all the test cases are failing in a spec file, update their names as mentioned above and demote the spec file.
```suggestion
   3. If all the test cases are failing in a spec file, update each title as mentioned above and demote the spec file.
```

2022-03-22 06:29 UTC, saturninoabril commented on site/content/contribute/mobile/e2e/guide-for-writing.md
> +   1. link the failed test case/s to Jira issue, `Goto Jira Bug > Click Zephyr Scale tab > Click 'add an existing one' link > Select test case/s > Click Add`
```suggestion
   4. Link the failed test case/s to Jira issue, `Go to Jira Bug > Click Zephyr Scale tab > Click 'add an existing one' link > Select test case/s > Click Add`
```

2022-03-22 06:29 UTC, saturninoabril commented on site/content/contribute/webapp/e2e/guide-for-writing.md
> +
Same suggestions as above.

2022-03-22 13:47 UTC, Phrynobatrachus approved these changes

2022-03-22 14:02 UTC, cwarnermm reviewed
Great update, @furqanmlk! I've provided feedback inline. Please let me know if you have any questions or concerns.

2022-03-23 03:54 UTC, saturninoabril approved these changes
Thanks @furqanmlk! Approving now given all comments are resolved.

2022-03-23 15:57 UTC, furqanmlk commented
Thanks @cwarnermm for detailed review

2022-03-23 16:14 UTC, cwarnermm approved these changes
Thanks!

2022-03-23 19:13 UTC, cwarnermm commented on site/content/contribute/mobile/e2e/guide-for-writing.md
> +   4. Link the failed test case/s to the Jira issue. In the Jira bug, select the **Zephyr Scale** tab. Select the **add an existing one** link, then select test case/s, and select **Add**.
```suggestion
   4. Link the failed test cases to the Jira issue. In the Jira bug, select the **Zephyr Scale** tab. Select the **add an existing one** link, then select test cases, and select **Add**.
```

2022-03-23 19:15 UTC, merged