Apps Framework updates
mattermost/mattermost-developer-documentation pull request #1060
Opened 2022-04-22 21:02 UTC by cwarnermm

In preparation for the v7.0 launch in June, Docs is proposing updates to the Apps Framework developer documentation to reduce the barriers to entry for the greatest number of developers and integrators.

2022-06-09 21:16 UTC, wiersgallak requested changes
Added some comments/content for you to consider

2022-06-09 21:16 UTC, wiersgallak commented on site/content/integrate/apps/_index.md
> +*[what is it and how does it differ from the existing plugin framework?]*
App framework wraps the Mattermost API into a tool making it easy to develop integrations that interact with the Mattermost Server and Web App in predefined ways. 

They are different than plugins in that plugins have the ability to modify the Mattermost Server and Web App without having to fork those specific repositories.

2022-06-09 21:16 UTC, wiersgallak commented on site/content/integrate/apps/_index.md
> +## Try the test app
Check out these sample apps: 
 - [ServiceNow](https://mattermost.com/marketplace/servicenow-app/) 
 - [Zendesk](https://mattermost.com/marketplace/zendesk-app/)

2022-10-07 17:41 UTC, cwarnermm commented
Closing this PR in favour of other PRs being merged into the code base.

2022-10-07 17:41 UTC, closed without merging