Update macos.md - M1 arch
mattermost/mattermost-developer-documentation pull request #1110
Opened 2022-09-08 13:17 UTC by tboulis

Add instructions for Macs with M1 chips

2022-09-08 13:30 UTC, neflyte requested changes

2022-09-08 13:30 UTC, neflyte commented on site/content/contribute/desktop/developer-setup/macos.md
> +For Mac with Apple Chip (M1 architecture):
```suggestion
For machines using the M1 architecture:
```

2022-09-08 13:30 UTC, neflyte commented on site/content/contribute/desktop/developer-setup/macos.md
> +- Use the latest NodeJS@16 (>=v16.16)
```suggestion
2. Use the latest NodeJS@16 (>=v16.16)

```

2022-09-08 13:30 UTC, neflyte commented on site/content/contribute/desktop/developer-setup/macos.md
> +- Update [xcode](https://developer.apple.com/xcode/) to latest version (>=v13.4.1)
```suggestion
3. Update [xcode](https://developer.apple.com/xcode/) to latest version (>=v13.4.1)

```

2022-09-08 13:31 UTC, neflyte commented
Thanks for the contribution, @tboulis. I've left a few suggestions to bring this change in line with the current documentation format.

2022-09-08 14:15 UTC, devinbinnie approved these changes

2022-09-15 16:22 UTC, neflyte approved these changes

2022-09-15 16:43 UTC, M-ZubairAhmed commented
i am not sure if we should mention latest node 16 though i remember having problems. At the very least stick to the version exactly which is the web app ?

2022-10-03 14:25 UTC, cwarnermm commented
@tboulis - Are you open to address the merge conflicts on this PR?

2022-10-03 14:44 UTC, merged