Update windows-wsl.md
mattermost/mattermost-developer-documentation pull request #1113
Opened 2022-09-12 20:29 UTC by WilliamLongKing

Based off my experience in setting up my server environment using WSL2, I found it much easier to follow the official Docker instructions, which did not require many of the instructions from steps 1 and 2. I also encountered the error added in the troubleshooting section, which I thought would be helpful to add.

#### Summary

#### Ticket Link

2022-10-04 12:21 UTC, neflyte commented
/update-branch

2022-10-04 12:21 UTC, mattermod commented
Looks like you don't have permissions to trigger this command.
 Only available for the PR submitter and org members

2022-10-04 12:21 UTC, neflyte commented
@WilliamLongKing Thanks for your contribution! Please update your branch to resolve the conflicts. :)

2022-10-04 12:22 UTC, neflyte requested changes
This content has been moved. Please update your branch and resolve conflicts.

2022-10-25 17:41 UTC, WilliamLongKing commented
/update-branch

2022-10-25 17:41 UTC, mattermod commented
Error trying to update the PR.
Please do it manually.

2022-11-28 10:05 UTC, AshishDhama commented
@WilliamLongKing Please feel add me again once you are done. cc// @cwarnermm

2022-11-28 16:10 UTC, closed without merging