chore(webapp): added note for apple silicon macs
mattermost/mattermost-developer-documentation pull request #1160
Opened 2022-10-18 09:51 UTC by fmartingr

#### Summary
Added a note regarding Apple Silicon Macs requiring Rosetta to be installed for al package.json dependencies and libraries to work ok.

I didn't find any Apple oficial documentation regarding the `softwareupdate` command, that's why I just put it in there.

2022-10-18 09:51 UTC, mattermod commented
Hello @fmartingr,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-10-18 12:45 UTC, neflyte requested changes

2022-10-18 12:45 UTC, neflyte commented on site/content/contribute/more-info/webapp/developer-setup.md
> +If you are working with an [Apple Silicon Mac](https://support.apple.com/en-us/HT211814) you may need to install rosetta for dependencies not ready to work in an ARM machine to work properly:
```suggestion
If you are working with an {{<newtabref title="Apple Silicon Mac" href="https://support.apple.com/en-us/HT211814">}} you may need to install rosetta for dependencies not ready to work in an ARM machine to work properly:
```

2022-10-18 21:01 UTC, hmhealey approved these changes

2022-10-19 12:24 UTC, cwarnermm approved these changes
Thank you, @fmartingr!

2022-10-19 12:24 UTC, merged