Fix GitHub Casing
mattermost/mattermost-developer-documentation pull request #1191
Opened 2022-12-17 05:12 UTC by varghesejose2020

2022-12-17 05:12 UTC, mattermod commented
Hello @varghesejose2020,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-12-19 21:32 UTC, cwarnermm approved these changes
Thank you, @varghesejose2020!

2022-12-20 15:56 UTC, neflyte requested changes

2022-12-20 15:56 UTC, neflyte commented on site/content/contribute/more-info/mobile/build-your-own/_index.md
>  {{<note "Note:">}}
```suggestion
{{</note>}}
```
Please make sure to close the `note` tag at the end of the note. :slightly_smiling_face:

2022-12-20 15:56 UTC, neflyte commented on site/content/contribute/more-info/mobile/build-your-own/_index.md
> +---
Please remove this horizontal line.

2022-12-20 15:56 UTC, neflyte commented on site/content/contribute/more-info/mobile/build-your-own/_index.md
> +---
Please remove this horizontal line as well.

2022-12-20 15:57 UTC, neflyte commented
Please make sure to test your changes locally or with the preview environment. Here's what I see in the preview:

![image](https://user-images.githubusercontent.com/18126609/208710048-a5105119-2ce0-4f94-ad2a-9169447d17cb.png)

2022-12-20 16:34 UTC, varghesejose2020 commented
Changes updated @cwarnermm

2022-12-22 14:35 UTC, neflyte approved these changes

2023-01-02 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-01-09 16:42 UTC, varghesejose2020 commented
@cwarnermm

2023-01-09 17:02 UTC, cwarnermm commented on site/content/contribute/more-info/mobile/build-your-own/_index.md
> +{{</note>}}
@varghesejose2020 - Please delete the note syntax on line 19. The note title is set via line 17.

2023-01-09 17:03 UTC, cwarnermm requested changes
Thanks, @varghesejose2020! I've identified one line that should be removed from the commmitted changes. Once that change is applied, I can merge this PR.

Thank you for updating the copyright notice in the footer too! Very much appreciated!!

2023-01-13 08:13 UTC, varghesejose2020 commented
@cwarnermm  changes updated

2023-01-18 14:31 UTC, cwarnermm commented on site/content/contribute/more-info/mobile/build-your-own/_index.md
>  **Note:** By using the **scripts**, {{< newtabref href="https://docs.fastlane.tools/#choose-your-installation-method" title="Fastlane" >}} and other dependencies will be installed in your system.
```suggestion
By using the **scripts**, {{< newtabref href="https://docs.fastlane.tools/#choose-your-installation-method" title="Fastlane" >}} and other dependencies will be installed in your system.
```

2023-01-23 13:45 UTC, merged