Update personal access token docs screenshots
mattermost/mattermost-developer-documentation pull request #1310
Opened 2023-10-22 17:40 UTC by aniketh-varma

#### Summary
Updated the screenshots for the personal access tokens docs

#### Ticket Link
Fixes https://github.com/mattermost/docs/issues/6653

2023-10-22 17:40 UTC, mattermost-build commented
Hello @aniketh-varma,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-23 13:33 UTC, cwarnermm requested changes

2023-10-23 13:33 UTC, cwarnermm commented on site/content/integrate/reference/personal-access-token/_index.md
> +    ![image](access_token_profile.png)
@aniketh-varma

1. This screenshot isn't correct. Please refer to the [existing docs page](https://developers.mattermost.com/integrate/reference/personal-access-token/) as a reference.
2. Avoid renaming screenshot files. Please reuse the same filename.
3. Ensure that file extensions are lowercase (not PNG).

2023-10-23 13:33 UTC, cwarnermm commented on site/content/integrate/reference/personal-access-token/_index.md
> +    ![image](access_token_enable.png)
@aniketh-varma

1. This screenshot isn't correct. Please refer to the [existing docs page](https://developers.mattermost.com/integrate/reference/personal-access-token/) as a reference.
2. Avoid renaming screenshot files. Please reuse the same filename.

2023-10-27 08:14 UTC, hanzei requested changes
Blocking on https://github.com/mattermost/mattermost-developer-documentation/pull/1310#discussion_r1368679487

2023-11-09 21:53 UTC, cwarnermm commented
@aniketh-varma - Are you open to applying the feedback provided in this PR?

2023-12-18 21:47 UTC, cwarnermm commented
@aniketh-varma - Are you open to applying the feedback provided in this PR?

2023-12-29 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-01-08 16:51 UTC, cwarnermm commented
@aniketh-varma - Are you open to applying the feedback provided in this PR?

2024-01-16 13:41 UTC, cwarnermm commented
Closing due to inactivity.

2024-01-16 13:41 UTC, closed without merging