[GH-1309] Correct Attachments documentation
mattermost/mattermost-developer-documentation pull request #1324
Opened 2023-12-30 09:18 UTC by Omar8345

#### Summary

This pull request corrects misinformation in the [attachments documentation](https://developers.mattermost.com/integrate/reference/message-attachments/), in the end of the documentation, it instructs the developer to add an `attachment` key in the `prop` field, which won't work, I have edited the documentation and the curl and HTTPS examples to add the `attachment` key in the top-level of the post's JSON.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/1309

2023-12-30 09:18 UTC, mattermost-build commented
Hello @Omar8345,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-01-08 15:31 UTC, cwarnermm commented
Thanks, @Omar8345, for this developer documentation PR. Your changes will be technically reviewed by Engineering.

2024-01-10 20:45 UTC, hmhealey requested changes
Thanks for the PR, @Omar8345! I think there might be some confusion going on here because the syntax in those examples matches how `POST /api/v4/posts` expects the payload to look.

When you tried this, were you perhaps using an incoming webhook? I think the payload sent to a webhook uses the `attachments` field without `props` like in your changes.

If that's the case, I think we could instead add a separate example for posting message attachments using a webhook. If we do that, we should probably also update the existing examples to be posting to `https://{your-mattermost-site}/api/v4/posts` since that's the correct API endpoint for that

2024-01-11 11:15 UTC, Omar8345 commented
> Thanks for the PR, @Omar8345! I think there might be some confusion going on here because the syntax in those examples matches how `POST /api/v4/posts` expects the payload to look.
> 
> When you tried this, were you perhaps using an incoming webhook? I think the payload sent to a webhook uses the `attachments` field without `props` like in your changes.
> 
> If that's the case, I think we could instead add a separate example for posting message attachments using a webhook. If we do that, we should probably also update the existing examples to be posting to `https://{your-mattermost-site}/api/v4/posts` since that's the correct API endpoint for that

Thanks for your catch, I have made the corresponding changes requested and added a section for how to post a message attachment using a webhook.

2024-01-11 19:09 UTC, hmhealey approved these changes
Thanks for adding that! I'm sure I'll find this useful since I've always needed to manually construct the curl command for this when I occasionally need to test something involving message attachments. I've got a couple minor tweaks I want to make, but they're more nitpicky so I can apply them myself

2024-01-11 19:09 UTC, hmhealey commented on site/content/integrate/reference/message-attachments/_index.md
> +Yes, you can also use the {{< newtabref href="https://api.mattermost.com/#operation/CreatePost" title="create post RESTful API" >}} to post a message attachment using a webhook.
```suggestion
Yes, you can also use an [incoming webhook]({{< ref "/integrate/webhooks/incoming" >}}) to post a message attachment.
```

2024-01-11 19:09 UTC, hmhealey commented on site/content/integrate/reference/message-attachments/_index.md
> +`curl -i -X POST -H 'Content-Type: application/json' -d '{"text":"Test message #testing", "attachments": [{"pretext": "This is the attachment pretext.","text": "This is the attachment text."}]}' http
```suggestion
`curl -i -X POST -H 'Content-Type: application/json' -d '{"text":"Test message #testing", "attachments": [{"pretext": "This is the attachment pretext.","text": "This is the attachment text."}]}' https://{your-mattermost-site}/hooks/{your-webhook-id}`
```

2024-01-11 19:09 UTC, hmhealey commented on site/content/integrate/reference/message-attachments/_index.md
> +POST /api/v4/posts HTTP/1.1
```suggestion
POST /hooks/{your-webhook-id} HTTP/1.1
```

2024-01-11 19:10 UTC, hmhealey requested changes
Actually, would you be able to apply those? I guess I don't have the required permission to do that here

2024-01-12 07:16 UTC, Omar8345 commented
> Actually, would you be able to apply those? I guess I don't have the required permission to do that here

Applied your suggested edits! I was a bit confused 😅

2024-01-12 14:05 UTC, cwarnermm commented
@Omar8345 - Can you update your branch with latest master, please? Thanks!

2024-01-12 14:08 UTC, Omar8345 commented
Done @cwarnermm

2024-01-12 14:29 UTC, devinbinnie approved these changes

2024-01-15 14:05 UTC, cwarnermm commented
@hmhealey - This PR is ready for your review.

2024-01-15 21:16 UTC, hmhealey approved these changes
Great catch! I remember mentioning to do that, but I forgot to confirm that it was done in both parts. Thanks for fixing that!

2024-01-15 21:16 UTC, merged