Update developer-setup.md to provide no-docker setup
mattermost/mattermost-developer-documentation pull request #1351
Opened 2024-03-24 22:55 UTC by sinansonmez

#### Summary
Update developer-setup.md to provide no-docker setup information

2024-03-24 22:55 UTC, mattermost-build commented
Hello @sinansonmez,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-03-25 13:15 UTC, cwarnermm requested changes
Thanks, @sinansonmez. Provided editorial feedback.

2024-03-25 13:15 UTC, cwarnermm commented on site/content/contribute/developer-setup.md
> +1. Install [Docker](https://www.docker.com/). If you dont want to use Docker, you can follow the steps in the sub-bullets for manual database setup
```suggestion
1. Install [Docker](https://www.docker.com/). If you don't want to use Docker, you can follow the steps in the sub-bullets below for manual database setup.
```

2024-03-25 13:15 UTC, cwarnermm commented on site/content/contribute/developer-setup.md
> +    1. Zet `MM_NO_DOCKER` to `true` in `server/config.mk` file
```suggestion
    1. Set `MM_NO_DOCKER` to `true` in the `server/config.mk` file.
```

2024-03-25 13:15 UTC, cwarnermm commented on site/content/contribute/developer-setup.md
> +    4. Modify the role to give rights to create ` database by running `ALTER ROLE mmuser CREATEDB;`
```suggestion
    4. Modify the role to give rights to create a database by running `ALTER ROLE mmuser CREATEDB;`
```

2024-03-25 13:15 UTC, cwarnermm commented on site/content/contribute/developer-setup.md
> +    5. Check the role by running `\du`
```suggestion
    5. Confirm the role rights by running `\du`
```

2024-03-25 13:15 UTC, cwarnermm commented on site/content/contribute/developer-setup.md
> +    7. Login again via mmuser by running `psql postgres -U mmuser`
```suggestion
    7. Login again via `mmuser` by running `psql postgres -U mmuser`
```

2024-03-25 16:55 UTC, hmhealey requested changes
When you make those changes, could you move those steps to a separate section at the bottom of the doc and change that "Install Docker" step to point the user to the new section if they don't want to use Docker? I think we should split those steps into their own section because I think people will miss that those steps are optional and go through them after installing Docker. I want to keep the main instructions simpler because I screw up complicated instructions all the time 😅

2024-03-26 22:57 UTC, sinansonmez commented
> When you make those changes, could you move those steps to a separate section at the bottom of the doc and change that "Install Docker" step to point the user to the new section if they don't want to use Docker? I think we should split those steps into their own section because I think people will miss that those steps are optional and go through them after installing Docker. I want to keep the main instructions simpler because I screw up complicated instructions all the time 😅

@hmhealey @cwarnermm Thanks for the feedback. Unfortunately, it is not clear to me how to proceed. 

Currently there are 3 main sections
- Set up your development environment 
- Prerequisites for Windows
- Setup the Mattermost Server 

Under `Setup the Mattermost Server ` there are 13 steps. Should I create a new main section or add the 14th step under `Setup the Mattermost Server ` ?

2024-03-27 13:38 UTC, cwarnermm commented
Hi @sinansonmez! The ask is to separate the Docker steps within their own section (at the top of the page as the primary way forward) from the not-using-Docker steps you're providing. @hmhealey is suggesting we move the non-Docker info to its own section elsewhere on the page to avoid reader confusion.

The reader's experience would look like this:
- Reader reaches the **Setup the Mattermost Server** section.
- Step 2 instructs them to install Docker. Step 2 also includes a link to the new non-Docker section later on the page in case the reader would prefer that approach.
- The rest of this section is about using Docker.

Meanwhile, following the **Setup the Mattermost Server** section, there's a new section about setting up Mattermost Server without Docker. That's where your steps would live.

2024-03-27 14:24 UTC, hmhealey commented
Yep, that's right. So with your steps, there'd be 4 sections:
- Set up your development environment
- Prerequisites for Windows
- Setup the Mattermost Server
- Develop Mattermost without Docker

2024-03-27 22:06 UTC, sinansonmez commented
thanks for the explanation @hmhealey @cwarnermm the page is updated as requested

2024-03-28 13:19 UTC, cwarnermm approved these changes
Thanks, @sinansonmez!

2024-03-28 22:22 UTC, hmhealey approved these changes
Thanks, Sinan!

2024-03-28 22:22 UTC, merged