Allow copy left plugins in the Marketplace
mattermost/mattermost-developer-documentation pull request #691
Opened 2020-09-25 21:48 UTC by hanzei

#### Summary
As discussed on Community there is no need to prohibit copy left plugins in the Marketplace.

#### Ticket Link
https://community.mattermost.com/private-core/pl/mk66rxs8etbffd8gc9bg9mfone

2020-09-27 03:02 UTC, jasonblais requested changes
If we do get a plugin submission with a copy left license, we'll have a legal review at that point to confirm there are no concerns, correct?

2020-09-27 03:02 UTC, jasonblais commented on site/content/extend/plugins/community-plugin-marketplace.md
> +1. The plugin is published under an [Open Source license](https://opensource.org/osd-annotated).
Proposed update as this link is used by Atlassian and GitLab for their open source programs
 - https://opensource.org/licenses/alphabetical
 - https://opensource.org/licenses/category

2020-09-27 05:57 UTC, hanzei commented
> If we do get a plugin submission with a copy left license, we'll have a legal review at that point to confirm there are no concerns, correct?

Yes, we should do that.

2020-09-27 13:25 UTC, jasonblais approved these changes
Is the legal review included in a process somewhere? Otherwise it'll be forgotten if a copy-left license is submitted a year from now, for instance?

2020-09-28 10:29 UTC, hanzei commented
The process owner i.e. me checks what license a submitted plugins has. Confirming that the license doesn't contain parts that Mattermost can't fulfill, is part of that check. 2/5 that a todo to do legal review shouldn't be part of this document as the audience are community members.

2020-09-28 17:38 UTC, jespino approved these changes
LGTM

2020-09-28 21:28 UTC, merged