address issues #732
mattermost/mattermost-developer-documentation pull request #742
Opened 2020-12-05 15:19 UTC by TaylorWesker

#### Summary
changed `npm -g install react-native-cli` to `sudo npm -g install react-native-cli` in `site/contribute/mobile/developer-setup/_index.md` line 78

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/732

2020-12-05 15:19 UTC, mattermod commented
Hello @TaylorWesker,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-12-07 17:01 UTC, enahum requested changes
I would decline this PR

2020-12-07 21:28 UTC, TaylorWesker commented on site/content/contribute/mobile/developer-setup/_index.md
> +$ sudo npm -g install react-native-cli
Got it, should I close the pull request now, or wait for the second reviewer to give his though ?

2020-12-07 23:36 UTC, TaylorWesker commented on site/content/contribute/mobile/developer-setup/_index.md
> +$ sudo npm -g install react-native-cli
Ok, I'm closing the pull request.

2020-12-07 23:36 UTC, closed without merging