Update community-plugin-marketplace.md
mattermost/mattermost-developer-documentation pull request #747
Opened 2020-12-18 16:11 UTC by justinegeffen

Removed double line breaks, changes high-availability to High Availability.

2021-01-14 15:54 UTC, hanzei approved these changes

2021-01-18 13:45 UTC, jasonblais approved these changes
One non-blocking proposal

2021-01-18 13:45 UTC, jasonblais commented on site/content/extend/plugins/community-plugin-marketplace.md
> +2. The `plugin.json` file should include formatting consistent with the System Console UI. For assistance with this, you can visit the [Documentation channel](https://community.mattermost.com/core/ch
```suggestion
2. The `plugin.json` file should include formatting consistent with the System Console UI. You can join the [Documentation channel](https://community.mattermost.com/core/channels/documentation) for assistance.
```

2021-01-19 16:31 UTC, hanzei requested changes
Heads up that the changes here will need to get propagated to https://github.com/mattermost/mattermost-marketplace/blob/master/.github/ISSUE_TEMPLATE/add_plugin.md. @justinegeffen is that something you can do after this PR is merged?

2021-01-19 16:31 UTC, hanzei commented on site/content/extend/plugins/community-plugin-marketplace.md
> +2. The `plugin.json` file should include formatting consistent with the System Console UI. For assistance with this, you can visit the [Documentation channel](https://community.mattermost.com/core/ch
Are there any docs about the style guidelines that we can link?

2021-01-19 16:31 UTC, hanzei commented on site/content/extend/plugins/community-plugin-marketplace.md
> +    * Link or email address for help/support
With these items in place does that mean item 4. at "Product requirements" is not longer needed? Should we combine those?

2021-01-19 16:31 UTC, hanzei commented on site/content/extend/plugins/community-plugin-marketplace.md
> +    * Link or email address for help/support
Can the support link just be the github issues page? If so, what is the difference to item 3 on "Product requirements"?

2021-01-27 19:59 UTC, justinegeffen commented on site/content/extend/plugins/community-plugin-marketplace.md
> +    * Link or email address for help/support
Good catch. I'll combine them.

2021-09-02 15:40 UTC, justinegeffen commented on site/content/extend/plugins/community-plugin-marketplace.md
>  7. All configuration is accessible via the Mattermost UI.
```suggestion
7. All configuration is accessible via the Mattermost interface.
```

2021-09-02 15:40 UTC, justinegeffen commented on site/content/extend/plugins/community-plugin-marketplace.md
>  8. The plugin ID defined in the manifest must not collide with the ID of an existing plugin in the Plugin Marketplace. It should follow [the documentation's suggested naming convention](https://devel
```suggestion
8. The plugin ID defined in the manifest must not collide with the ID of an existing plugin in the Marketplace. It should follow [the documentation's suggested naming convention](https://developers.mattermost.com/extend/plugins/manifest-reference/#id).
```

2021-09-02 15:51 UTC, closed without merging