update docs and screenshots around iOS notifications / certificates
mattermost/mattermost-developer-documentation pull request #750
Opened 2021-01-07 15:27 UTC by chrisfromredfin

#### Summary
As the UI of Apple Developer has changed, the screenshots and process for generating a push notifications certificate have also changed. This PR updates both the screenshots and process for generating a certificate as well as using Keychain Access and openssl from the CLI to generate a certificate that works with mattermost-push-proxy.

2021-01-07 15:27 UTC, mattermod commented
Hello @chrisfromredfin,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-01-14 12:44 UTC, enahum requested changes
one small typo, the rest looks good.

Thanks @chrisfromredfin

2021-01-14 12:44 UTC, enahum commented on site/content/contribute/mobile/push-notifications/service.md
> +- Double click the **Push Notifications Certificate** generated and downloading while [Setting up Push Notifications for iOS](/contribute/mobile/push-notifications/ios) to add it to your Keychain Acc
```suggestion
- Double click the **Push Notifications Certificate** generated and downloaded while [Setting up Push Notifications for iOS](/contribute/mobile/push-notifications/ios) to add it to your Keychain Access (downloads by default as aps.cer).
```

2021-01-14 15:56 UTC, enahum approved these changes

2021-01-25 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-01-26 16:53 UTC, jfrerich commented
@justinegeffen, gentle ping for review!

2021-01-26 18:08 UTC, justinegeffen reviewed
I've added some questions around the wording suggestions. Once you've had a look please feel free to request another review, or alternatively just let me know and I can create a new PR for additional changes.

2021-01-26 18:08 UTC, justinegeffen commented on site/content/contribute/mobile/push-notifications/service.md
> +This could also be because you generated a certificate for the wrong bundle ID. The bundle ID used in mattermost-push-proxy.json should be the same one as the app and the same that you generated the
@jfrerich, I don't know if my rewording makes sense - LMK what the paragraph refers to. :)

2021-02-15 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-03-22 14:54 UTC, chrisfromredfin commented
!Ping another reviewer?

2021-04-26 14:53 UTC, justinegeffen commented
Hi @chrisfromredfin! I've gone ahead and committed my suggestions. If you're open to reviewing the doc and letting me know if it all makes sense then we can go ahead and merge. :)

2021-04-26 19:01 UTC, chrisfromredfin commented on site/content/contribute/mobile/push-notifications/service.md
> +**For iOS / Apple Push Notifications**: If the logs are reflecting DeviceTokenNotForTopic (error 400)
👍🏼

2021-04-26 19:03 UTC, chrisfromredfin commented
I was just wondering about this PR today! What crazy timing. All of this looks fantastic to me!

2021-04-27 11:20 UTC, jasonblais commented
@justinegeffen is this one then ready to merge?

@chrisfromredfin thanks for your contribution! :)

2021-04-27 14:07 UTC, justinegeffen approved these changes

2021-04-27 14:07 UTC, merged