Update index: Link to go driver
mattermost/mattermost-developer-documentation pull request #820
Opened 2021-05-04 18:45 UTC by justinegeffen

Added link to Go repo.

2021-05-04 19:00 UTC, aaronrothschild approved these changes

2021-05-05 05:36 UTC, hanzei requested changes

2021-05-05 05:36 UTC, hanzei commented on site/content/integrate/apps/_index.md
> +Any language you want. We currently have an [official driver for Go](https://github.com/mattermost/mattermost-plugin-apps/tree/master/apps), and we are planning to release other drivers in the future
Let's link to godoc instead
```suggestion
Any language you want. We currently have an [official driver for Go](https://pkg.go.dev/github.com/mattermost/mattermost-plugin-apps/apps), and we are planning to release other drivers in the future in conjunction with our community.
```

2021-05-05 09:28 UTC, hanzei approved these changes

2021-05-05 09:41 UTC, merged