Update community_process.md
mattermost/mattermost-developer-documentation pull request #908
Opened 2021-08-06 20:54 UTC by Sayanta66

Fixed broken link and updated one

#### Summary

#### Ticket Link

2021-08-06 20:54 UTC, mattermod commented
Hello @Sayanta66,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-08-07 16:13 UTC, justinegeffen commented on site/content/extend/plugins/community_process.md
> +Getting your plugin onto our Community server https://community.mattermost.com is a valuable source of feedback. Whether you are a [Core Committer](https://developers.mattermost.com/contribute/gettin
```suggestion
Getting your plugin onto our Community server https://community.mattermost.com is a valuable source of feedback. Whether you are a [Core Committer](https://handbook.mattermost.com/contributors/contributors/core-committers) or anyone from the community, we want you to get feedback to improve your plugin.
```

2021-08-07 16:15 UTC, justinegeffen commented on site/content/extend/plugins/community_process.md
> +However we must ensure that our Community server remains stable for everyone. This document outlines the process of getting your plugin onto the Community server and some of these steps are required
The existing link points to a page with all the steps needed to follow to list a plugin in the Plugin Marketplace. Having the URL point to the Plugin Marketplace works in some cases but in this case it doesn't. I have reverted this change. Thank you!

2021-08-07 16:15 UTC, justinegeffen commented on site/content/extend/plugins/community_process.md
> +However we must ensure that our Community server remains stable for everyone. This document outlines the process of getting your plugin onto the Community server and some of these steps are required
```suggestion
However we must ensure that our Community server remains stable for everyone. This document outlines the process of getting your plugin onto the Community server and some of these steps are required to get your plugin into the [Plugin Marketplace](/extend/plugins/community-plugin-marketplace/).
```

2021-08-09 13:43 UTC, cwarnermm requested changes
Thank you for your docs contribution! I've provided feedback inline.

2021-08-09 13:43 UTC, cwarnermm commented on site/content/extend/plugins/community_process.md
> +Getting your plugin onto our Community server https://community.mattermost.com is a valuable source of feedback. Whether you are a [Core Committer](https://handbook.mattermost.com/contributors/contri
```suggestion
Getting your plugin onto our [Community server](https://community.mattermost.com) is a valuable source of feedback. Whether you are a [Core Committer](https://handbook.mattermost.com/contributors/contributors/core-committers) or anyone from the community, we want you to get feedback to improve your plugin.
```

2021-08-09 13:43 UTC, cwarnermm commented on site/content/extend/plugins/community_process.md
> +However we must ensure that our Community server remains stable for everyone. This document outlines the process of getting your plugin onto the Community server and some of these steps are required
```suggestion
However we must ensure that our Community server remains stable for everyone. This document outlines the process of getting your plugin onto the Community server. Some of these steps are also required to get your plugin into the [Plugin Marketplace](/extend/plugins/community-plugin-marketplace/).
```

2021-08-13 07:31 UTC, justinegeffen commented
This page was updated as part of a separate PR and was moved to another section which is why there are conflicts. As this PR is not going to be applied, I am closing it but not marking it as invalid because it was an inadvertent conflict.

2021-08-13 07:31 UTC, closed without merging