Include info about running plugins with scheduled jobs in HA
mattermost/mattermost-developer-documentation pull request #909
Opened 2021-08-06 20:57 UTC by mickmister

#### Summary

This PR adds a section to the plugin High Availability page, mentioning the [mattermost-plugin-api/cluster](https://github.com/mattermost/mattermost-plugin-api/blob/37eccf0f0f3e9e0737d017b555ef3e2e720b3021/cluster/job.go#L112) package that allows plugins to run scheduled jobs in an HA environment.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/672

2021-08-07 17:13 UTC, justinegeffen approved these changes
Awesome update, thank you @mickmister!

2021-08-09 13:40 UTC, cwarnermm requested changes
Thank you for your docs contribution. I've provided feedback inline.

2021-08-09 13:40 UTC, cwarnermm commented on site/content/extend/plugins/server/ha.md
> +Using the [mattermost-plugin-api/cluster](https://github.com/mattermost/mattermost-plugin-api/blob/37eccf0f0f3e9e0737d017b555ef3e2e720b3021/cluster/job.go#L112) package, we can schedule jobs to perfo
```suggestion
Using the [mattermost-plugin-api/cluster](https://github.com/mattermost/mattermost-plugin-api/blob/37eccf0f0f3e9e0737d017b555ef3e2e720b3021/cluster/job.go#L112) package, we can schedule jobs to perform background activity at regular intervals, without having to explicitly coordinate with other instances of the same plugin. Here's an example from the [Demo Plugin](https://github.com/mattermost/mattermost-plugin-demo/blob/d647f1ed7fdc384f5bc163a6bba689ab4293704e/server/activate_hooks.go#L72):
```

2021-08-09 14:47 UTC, cwarnermm approved these changes
Thanks so much for this docs contribution!

2021-08-09 14:48 UTC, merged