mmclient not found. appsclient found instead [Go lang Quick Start guide]
mattermost/mattermost-developer-documentation pull request #938
Opened 2021-09-24 12:28 UTC by ramiyengar

#### Summary

In the Quick Start guide for Go lang, there are a couple of updates to get it working. This is likely a small update because working copies of the files have changed names (mmclient not found. appsclient found in the repo).

#### Ticket Link
No ticket found.

2021-09-24 12:28 UTC, mattermod commented
Hello @ramiyengar,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-09-27 08:17 UTC, hanzei requested changes
Thank you for the fix @ramiyengar :+1: 

One question before I merge the PR

2021-09-27 08:17 UTC, hanzei commented on site/content/integrate/apps/quick-start-go/_index.md
> +go get github.com/mattermost/mattermost-plugin-apps/utils/
Is this really needed? Where is the package getting used?

2021-09-27 13:59 UTC, levb approved these changes

2021-11-11 08:31 UTC, larkox approved these changes

2021-11-11 08:52 UTC, merged