Fix broken link to mobile app white label page
mattermost/mattermost-developer-documentation pull request #976
Opened 2021-12-29 07:05 UTC by mickmister

#### Summary

#### Ticket Link

2022-01-05 10:10 UTC, hanzei requested changes

2022-01-05 10:10 UTC, hanzei commented on site/content/contribute/mobile/build-your-own/android.md
> +| `REPLACE_ASSETS` | Override the assets as described in [White Labeling](/contribute/mobile/build-your-own/white-label/). <br><br>Valid values are: `true`, `false` | `false` | No |
Links should make use of [`ref`](https://gohugo.io/functions/ref/#readout) to catch issues like this.

2022-01-10 20:43 UTC, hanzei approved these changes

2022-01-11 13:37 UTC, justinegeffen approved these changes

2022-01-11 13:38 UTC, merged